config/routes.rb
Rails.application.routes.draw do

  resources :events
  resources :tipoincapacidads
  resources :tipoenfermedads
  resources :tiporiesgos
  resources :tipoincidentes
  resources :tipoaccidentes
  resources :albums
  resources :accidentes
  resources :municipios
  resources :departamentos
  

  get 'user_sessions/new'
  get 'user_sessions/create'
  get 'user_sessions/destroy'
  get 'email/send' => 'accidentes#enviar'
  
  resources :users

  match '/home', to: 'static_pages#home',  via: 'get' 
  match '/help',to: 'static_pages#help',  via: 'get' 
  match '/about',   to: 'static_pages#about',  via: 'get' 
  match '/contact', to: 'static_pages#contact',  via: 'get'
  match '/estadistica', to: 'static_pages#estadistica',  via: 'get' 
 
  root :to => 'user_sessions#index' 

  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/contact'
  get 'static_pages/about'
  get 'login' => 'user_sessions#new', :as => :login 
  get 'logout' => 'user_sessions#destroy', :as => :logout 
  get 'static_pages/estadistica'

  resources :incidentes
  resources :funcionarios

  resources :riesgos do 
    resources :tiporiesgos
  end

  resources :incapacidads do
    resources :tipoincapacidads
  end

  resources :accidentes do
    resources :tipoaccidentes
  end

  resources :enfermedads
  resources :personalinvolucrados
  resources :tipodocs
  resources :centros
  resources :user_sessions
  resources :users
  resources :cronogramas
  resources :tipo_salidas

  get 'incidentes_estadistica',to: 'incidentes#estadistica', :as => 'incidentes_estadistica'
  get 'riesgos_estadistica',to: 'riesgos#estadistica', :as => 'riesgos_estadistica'
  get 'enfermedads_estadistica',to: 'enfermedads#estadistica', :as => 'enfermedads_estadistica'
  get 'incapacidads_estadistica',to: 'incapacidads#estadistica', :as => 'incapacidads_estadistica'
  get 'accidentes_estadistica',to: 'accidentes#estadistica', :as => 'accidentes_estadistica'

  

   

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
 before_filter :require_login, :except => [:home, :help, :contact, :about] 
   
    
  def home
  end

  def help
  end

  def contact
  end

  def about
  end
  def estadistica
     tipo = params[:grafica] if params[:grafica]
  end

  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

end

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/estadistica.html.erb
<html>
<head>
<meta charset= "utf-8">
    <link href="css/estadistica.css" type="text/css" rel="stylesheet" >
<title>Estadistica</title>
</head>
<body >
<br>

<!-- Nav tabs -->
<div id="tab"><!--div para agragr estilo al tab -->
<ul class="nav nav-tabs" role="tablist">
  <li class="active color"><a href="#home" role="tab" data-toggle="tab">Estadistica Acidente</a></li>
  <li><a href="#profile" role="tab" data-toggle="tab" class="color">Estadistica Incidente</a></li>
  <li><a href="#messages" role="tab" data-toggle="tab" class="color">Estadistica riesgo</a></li>
  <li><a href="#settings" role="tab" data-toggle="tab" class="color">Estadistica Enfermedad</a></li>
  <li><a href="#ultima" role="tab" data-toggle="tab" class="color">Estadistica Incapacidad</a></li>
 
</ul>

<!-- todos los tab Tab, este es de ACCIDENTE  -->
<div class="tab-content">
<div class="tab-pane active" id="home"> 

<%= form_tag( accidentes_estadistica_path, method: 'get', remote: true) do |f| %><br>
<p>Seleccione el año agraficar las Estadísticas</p><br>
<select id="ano" name="ano">
  <option value="2014">2014</option>
  <option value="2015">2015</option>
  <option value="2016">2016</option>
</select>
<h3>Grafica de Accidentes</h3>

<!--grafica de torta de 3d-->
<%= link_to image_tag("pie_3d.jpg", title: 'grafica de barras', class: "imagen"),  accidentes_estadistica_path(grafica: "pie_3d"), remote: true %> 
<!--grafica de barras de 3d-->
<%= link_to image_tag("barras.png", title: 'grafica de barras', class: "imagen"),  accidentes_estadistica_path(grafica: "bar"), remote: true %> 
<!--grafica de line de 3d-->
<%= link_to image_tag("linechart.png", title: 'grafica de barras', class: "imagen"),  accidentes_estadistica_path(grafica: "line"), remote: true %> 

<% end %>
    
  </div>

<!-- grafica de incidentes con el tab-->

  <div class="tab-pane" id="profile">

<%= form_tag(incidentes_estadistica_path, method: 'get', remote: true) do |f| %><br>
<p>Seleccione el año agraficar las Estadísticas</p><br>
<select id="ano" name="ano">
  <option value="2014">2014</option>
  <option value="2015">2015</option>
  <option value="2016">2016</option>
</select>
<h3>Grafica de incidente</h3>

<!--grafica de torta de 3d-->
<%= link_to image_tag("pie_3d.jpg", title: 'grafica de barras', class: "imagen"), incidentes_estadistica_path(grafica: "pie_3d"), remote: true %> 
<!--grafica de barras de 3d-->
<%= link_to image_tag("barras.png", title: 'grafica de barras', class: "imagen"), incidentes_estadistica_path(grafica: "bar"), remote: true %> 
<!--grafica de line de 3d-->
<%= link_to image_tag("linechart.png", title: 'grafica de barras', class: "imagen"), incidentes_estadistica_path(grafica: "line"), remote: true %> 

<% end %>
  	
  </div>

  <div class="tab-pane" id="messages">
  <!--tab de riesgos-->
  	
 <%= form_tag(riesgos_estadistica_path, method: 'get', remote: true) do |f| %>
 <br>
<p>Seleccione el año agraficar las Estadísticas</p><br>
<select id="ano" name="ano">
	<option value="2014">2014</option>
	<option value="2015">2015</option>
	<option value="2016">2016</option>
</select>

<h3>Grafica de Riesgos</h3>

<%= link_to image_tag("pie_3d.jpg", title: 'grafica de barras', class: "imagen"), riesgos_estadistica_path(grafica: "pie_3d"), remote: true %> 
<!--grafica de barras de 3d-->
<%= link_to image_tag("barras.png", title: 'grafica de barras', class: "imagen"), riesgos_estadistica_path(grafica: "bar"), remote: true %> 
<!--grafica de line de 3d-->
<%= link_to image_tag("linechart.png", title: 'grafica de barras', class: "imagen"), riesgos_estadistica_path(grafica: "line"), remote: true %> 


<% end %>
  </div>
  <div class="tab-pane" id="settings">
    
 <%= form_tag(enfermedads_estadistica_path, method: 'get', remote: true) do |f| %><br>
<p>Seleccione el año agraficar las Estadísticas</p><br>
<select id="ano" name="ano">
  <option value="2014">2014</option>
  <option value="2015">2015</option>
  <option value="2016">2016</option>
</select>
<h3>Grafica de Enfermedades</h3>

<!--grafica de torta de 3d-->
<%= link_to image_tag("pie_3d.jpg", title: 'grafica de barras', class: "imagen"), enfermedads_estadistica_path(grafica: "pie_3d"), remote: true %> 
<!--grafica de barras de 3d-->
<%= link_to image_tag("barras.png", title: 'grafica de barras', class: "imagen"), enfermedads_estadistica_path(grafica: "bar"), remote: true %> 
<!--grafica de line de 3d-->
<%= link_to image_tag("linechart.png", title: 'grafica de barras', class: "imagen"), enfermedads_estadistica_path(grafica: "line"), remote: true %> 

<% end %>
    
  </div>
   <div class="tab-pane" id="ultima">



<%= form_tag(incapacidads_estadistica_path, method: 'get', remote: true) do |f| %><br>
<p>Seleccione el año agraficar las Estadísticas</p><br>
<select id="ano" name="ano">
  <option value="2014">2014</option>
  <option value="2015">2015</option>
  <option value="2016">2016</option>
</select>
<!--grafica por incapacidades-->
<h3>Grafica de Incapacidad</h3>

<%= link_to image_tag("pie_3d.jpg", title: 'grafica de barras', class: "imagen"), incapacidads_estadistica_path(grafica: "pie_3d"), remote: true %> 
<!--grafica de barras de 3d-->
<%= link_to image_tag("barras.png", title: 'grafica de barras', class: "imagen"), incapacidads_estadistica_path(grafica: "bar"), remote: true %> 
<!--grafica de line de 3d-->
<%= link_to image_tag("linechart.png", title: 'grafica de barras', class: "imagen"), incapacidads_estadistica_path(grafica: "line"), remote: true %> <br><br>

<% end %>
</div>
<div><!--fin del div -->

</body>
<div id="estadis">
<%= image_tag("estadistica1.gif") %>
</div>
</html>

app/views/static_pages/help.html.erb
<div class="ayu">
<div class="panel-group" id="accordion">
  <div class="panel">
    <div class="panel-heading tuno">
      <h4 class="panel-title tiayu ">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
          FUNCIONARIO
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in">
      <div class="panel-body">
        El modulo de funcionario tiene un buscador que te agiliza la busqueda de un registro especifico y lo podras hacer a traves del nonbre del funcionario.
        Posteriormente encontraras un boton "Nuevo Funcionario" que te permite crear un registro con los datos de un funcionario.
        Cada registro tiene las opciones de. Ver, Editar y Eliminar, estos los podras ver de acuerdo al rol que tengas en el sistema. 
        Y por ultimo tienes la opción de pasar de paginas despues de 5 registros dandole click en "siguiente" o "anterior" 
      </div>
    </div>
  </div>
  <div class="panel ">
    <div class="panel-heading tdos">
      <h4 class="panel-title tiayu">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
          NOVEDAD
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse">
      <div class="panel-body">
        <ol> 
  <li><h3>Accidente</h3></li>
  La opción de Accidente tiene un buscador que te agiliza la busqueda de un registro especifico y lo podras hacer a traves de la fecha.
  Posteriormente encontraras un boton "Nuevo Accidente" que te permite registrar una novedad en caso de un accidente.
  Si das click en el link de "Consultar Estadista" te mostrara las estadisticas de manera trimestral. 
  Cada registro tiene las opciones de. Ver, Editar y Eliminar, estos los podras ver de acuerdo al rol que tengas en el sistema.
  Y por ultimo tienes la opción de pasar de paginas despues de 5 registros dandole click en "siguiente" o "anterior"


  <li><h3>Incidente</h3></li>

  La opción de Incidente tiene un buscador que te agiliza la busqueda de un registro especifico y lo podras hacer a traves de la fecha de reporte.
  Posteriormente encontraras un boton "Nuevo Inccidente" que te permite registrar una novedad en caso de un incidente.
  Si das click en el link de "Consultar Estadista" te mostrara las estadisticas de manera trimestral. 
  Cada registro tiene las opciones de. Ver, Editar y Eliminar, estos los podras ver de acuerdo al rol que tengas en el sistema.
   Y por ultimo tienes la opción de pasar de paginas despues de 5 registros dandole click en "siguiente" o "anterior"

  <li><h3>Riesgo</h3></li>

  La opción de Riesgo tiene un buscador que te agiliza la busqueda de un registro especifico y lo podras hacer a traves de la empresa.
  Posteriormente encontraras un boton "Nuevo Riesgo" que te permite registrar una novedad de Riesgo en caso de ser requerido.
  Si das click en el link de "Consultar Estadista" te mostrara las estadisticas de manera trimestral. 
  Cada registro tiene las opciones de. Ver, Editar y Eliminar, estos los podras ver de acuerdo al rol que tengas en el sistema.
   Y por ultimo tienes la opción de pasar de paginas despues de 5 registros dandole click en "siguiente" o "anterior"

  <li><h3>Enfermedad</h3></li>

  La opción de Enfermedad tiene un buscador que te agiliza la busqueda de un registro especifico y lo podras hacer a traves de la fecha.
  Posteriormente encontraras un boton "Nueva Enfermedad" que te permite registrar una novedad en caso de enfermase un funcionario.
  Si das click en el link de "Consultar Estadista" te mostrara las estadisticas de manera trimestral. 
  Cada registro tiene las opciones de. Ver, Editar y Eliminar, estos los podras ver de acuerdo al rol que tengas en el sistema.
  Y por ultimo tienes la opción de pasar de paginas despues de 5 registros dandole click en "siguiente" o "anterior"

  <li><h3>Incapacidad</h3></li>

  La opción de Incapacidad tiene un buscador que te agiliza la busqueda de un registro especifico y lo podras hacer a traves de la fecha de inicio.
  Posteriormente encontraras un boton "Nueva Incapacidad" que te permite registrar una novedad en caso de ser requerido.
  Si das click en el link de "Consultar Estadista" te mostrara las estadisticas de manera trimestral. 
  Cada registro tiene las opciones de. Ver, Editar y Eliminar, estos los podras ver de acuerdo al rol que tengas en el sistema.
  Y por ultimo tienes la opción de pasar de paginas despues de 5 registros dandole click en "siguiente" o "anterior"
  </ol>
      </div>
    </div>
  </div>
  <div class="panel">
    <div class="panel-heading ttres">
      <h4 class="panel-title tiayu">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
          CRONOGRAMA
        </a>
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse">
      <div class="panel-body">
         El modulo de Cronogramas tiene un buscador que te agiliza la busqueda de un registro especifico y lo podras hacer a traves de la fecha.
        En la parte inferior encontraras un boton "Nuevo Cronograma" que te permite registrar una salida en caso de ser requerido.
        Cada registro tiene las opciones de. Ver, Editar y Eliminar, estos los podras ver de acuerdo al rol que tengas en el sistema.
        Y por ultimo tienes la opción de pasar de paginas despues de 5 registros dandole click en "siguiente" o "anterior"
               
  
      </div>
    </div>
  </div>
  <div class="panel ">
    <div class="panel-heading tcuatro">
      <h4 class="panel-title tiayu">
        <a data-toggle="collapse" data-parent="#accordion" href="#cuatro">
          ESTADISTICAS
        </a>
      </h4>
    </div>
    <div id="cuatro" class="panel-collapse collapse">
      <div class="panel-body">
        En este modulo encontraras de manera general las diferentes estadisticas que se genera en las opciones del modulo de novedad     
  
      </div>
    </div>
  </div>
  <div class="panel">
    <div class="panel-heading tcinco">
      <h4 class="panel-title tiayu">
        <a data-toggle="collapse" data-parent="#accordion" href="#cinco">
          GALERIA
        </a>
      </h4>
    </div>
    <div id="cinco" class="panel-collapse collapse">
      <div class="panel-body">
        En este modulo encontraras unos items para prevenir que hayan accidente, incidente, riesgo, enfermedad e incapacidad; tambien veras una serie de imgenes alusivas al area de salud ocupacional.      
  
      </div>
    </div>
  </div>
  <div class="panel">
    <div class="panel-heading tseis">
      <h4 class="panel-title tiayu">
        <a data-toggle="collapse" data-parent="#accordion" href="#seis">
          SEGURIDAD
        </a>
      </h4>
    </div>
    <div id="seis" class="panel-collapse collapse">
      <div class="panel-body">
        En este modulo se asignaran los diferentes roles del sistema, los cuales permitiran tener acceso limitado a operaciones como: Ver, Editar, Eliminar.
      </div>
    </div>
  </div>
  <div class="panel">
    <div class="panel-heading tsiete">
      <h4 class="panel-title tiayu">
        <a data-toggle="collapse" data-parent="#accordion" href="#siete">
          EDITAR PERFIL
        </a>
      </h4>
    </div>
    <div id="siete" class="panel-collapse collapse">
      <div class="panel-body">
        Esta opción le permite modificar los datos con los cuales antes de loguearse ingreso a la cuenta. Podras editar en él el password e email. 
  
      </div>
    </div>
  </div>
  <div class="panel">
    <div class="panel-heading tocho">
      <h4 class="panel-title tiayu">
        <a data-toggle="collapse" data-parent="#accordion" href="#ocho">
         SALIR
        </a>
      </h4>
    </div>
    <div id="ocho" class="panel-collapse collapse">
      <div class="panel-body">
       Esta opción te permite cerrar sesión, de esta forma tendras la seguridad de que otra persona no podra entrar a menos de que vuelva a iniciar sessión  
      </div>
    </div>
  </div>
</div>  
</div>

app/views/static_pages/home.html.erb
<html>
<head>
<title>Guia</title>
</head>
<body>

<div class="imainicio">
<img src="assets/mu.png" class="ima">
</div>


 <div id="border">
 <center class="fadeIn"><h1><b>¡ EMPECEMOS !</b></h1></center><br><br>


    <div class="cont">
<section class="main">
      
        <ul class="ch-grid">
          <li>
            <div class="ch-item ch-img-1">  
              <div class="ch-info-wrap">
                <div class="ch-info">     
                  <div class="ch-info-front ch-img-1"></div>
                  <h3 class="ti">Paso 1</h3> 
                  <div class="ch-info-back">
                    
                    <p>Ingresa al módulo de funcionarios podrá realizar un registro de sus datos personales para tener un control de todos los que reporten una novedad en el sistema.</p>
                  </div>  
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="ch-item ch-img-1">
              <div class="ch-info-wrap">
                <div class="ch-info">
                  <div class="ch-info-front ch-img-1"></div>
                  <h3 class="ti">Paso 2</h3> 
                  <div class="ch-info-back">
                    <p>Ingresa al módulo de novedad podrá registrar las diferentes eventualidades que se presenten en el área  de salud ocupacional y posteriormente podrá ver e interactuar con ellas.</p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="ch-item ch-img-1">
              <div class="ch-info-wrap">
                <div class="ch-info">
                  <div class="ch-info-front ch-img-1"></div>
                  <h3 class="ti">Paso 3</h3>
                  <div class="ch-info-back">
                    <p>Ingresa al módulo de cronograma podrá registrar las distintas salidas que se presenten fuera de la entidad.</p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="ch-item ch-img-1">
              <div class="ch-info-wrap">
                <div class="ch-info">
                  <div class="ch-info-front ch-img-1"></div>
                  <h3 class="ti">Paso 4</h3>
                  <div class="ch-info-back">
                    <p>Ingresa al módulo de estadística  podra obtener un informe detallado trimestralmente de las novedades que se presente como lo son  accidentes, incidentes, riesgo, incapacidad y enfermedades.</p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="ch-item ch-img-1">
              <div class="ch-info-wrap">
                <div class="ch-info">
                  <div class="ch-info-front ch-img-1"></div>
                  <h3 class="ti">Paso 5</h3>
                  <div class="ch-info-back">
                    <p>Ingresa  al módulo de galeria encontrara una serie de imágenes, con unos mensajes que hacen alusión a la prevención de las diferentes novedades.</p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="ch-item ch-img-1">
              <div class="ch-info-wrap">
                <div class="ch-info">
                  <div class="ch-info-front ch-img-1"></div>
                  <h3 class="ti">Paso 6</h3>
                  <div class="ch-info-back">
                    <p>Ingresa al módulo de editar perfil y podrá cambiar sus datos ingresados que fueron requeridos al registrarse en sistema</p>
                  </div>
                </div>
              </div>
            </div>
          </li>
        </ul>
        
      </section>
    </div>

   </div>  

</body>
</html> 