config/routes.rb
Rails.application.routes.draw do

  resources :events
  resources :tipoincapacidads
  resources :tipoenfermedads
  resources :tiporiesgos
  resources :tipoincidentes
  resources :tipoaccidentes
  resources :albums
  resources :accidentes
  resources :municipios
  resources :departamentos
  

  get 'user_sessions/new'
  get 'user_sessions/create'
  get 'user_sessions/destroy'
  get 'email/send' => 'accidentes#enviar'
  
  resources :users

  match '/home', to: 'static_pages#home',  via: 'get' 
  match '/help',to: 'static_pages#help',  via: 'get' 
  match '/about',   to: 'static_pages#about',  via: 'get' 
  match '/contact', to: 'static_pages#contact',  via: 'get'
  match '/estadistica', to: 'static_pages#estadistica',  via: 'get' 
 
  root :to => 'user_sessions#index' 

  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/contact'
  get 'static_pages/about'
  get 'login' => 'user_sessions#new', :as => :login 
  get 'logout' => 'user_sessions#destroy', :as => :logout 
  get 'static_pages/estadistica'

  resources :incidentes
  resources :funcionarios

  resources :riesgos do 
    resources :tiporiesgos
  end

  resources :incapacidads do
    resources :tipoincapacidads
  end

  resources :accidentes do
    resources :tipoaccidentes
  end

  resources :enfermedads
  resources :personalinvolucrados
  resources :tipodocs
  resources :centros
  resources :user_sessions
  resources :users
  resources :cronogramas
  resources :tipo_salidas

  get 'incidentes_estadistica',to: 'incidentes#estadistica', :as => 'incidentes_estadistica'
  get 'riesgos_estadistica',to: 'riesgos#estadistica', :as => 'riesgos_estadistica'
  get 'enfermedads_estadistica',to: 'enfermedads#estadistica', :as => 'enfermedads_estadistica'
  get 'incapacidads_estadistica',to: 'incapacidads#estadistica', :as => 'incapacidads_estadistica'
  get 'accidentes_estadistica',to: 'accidentes#estadistica', :as => 'accidentes_estadistica'

  

   

end

app/models/enfermedad.rb
class Enfermedad < ActiveRecord::Base   

 belongs_to :tipoenfermedad

	def self.search(search, page)
		where(['upper(fecha) like ?',
		"%#{search}%".upcase]).paginate(page: page, per_page: 5).order("fecha")
   end



  belongs_to :centro
  belongs_to :tipodoc
  belongs_to :funcionario

    validates :funcionario_id, :presence => true 
    validates :tipoenfermedad_id, :presence => true 
    validates :descripcion, :presence => true 
    validates :fecha, :presence => true 
    validates :codigodediagnostico, :presence => true 



    def self.to_csv(options = {})
         CSV.generate(options) do |csv|
         csv << column_names
         all.each do |enfermedad|
          csv << enfermedad.attributes.values_at(*column_names)
        end
       end
    end


   def self.estadistica_x_trimestre(fechIni, fechFin)
      @t1 = Enfermedad.select('count(*) as numero_enfermedads').where('fecha  between  ? and  ?',fechIni,fechFin)
      @t1.pluck('count(*)').first
   end
  
end

app/controllers/enfermedads_controller.rb
class EnfermedadsController < ApplicationController
  before_action :set_enfermedad, only: [:show, :edit, :update, :destroy]

 def estadistica
   @tipo = params[:grafica] 
   
   @ano = Hash.new
   @t1 = Enfermedad.estadistica_x_trimestre("2014-01-01", "2014-03-30")
   @t2 = Enfermedad.estadistica_x_trimestre("2014-04-01", "2014-06-30")
   @t3 = Enfermedad.estadistica_x_trimestre("2014-07-01", "2014-09-30")
   @t4 = Enfermedad.estadistica_x_trimestre("2014-10-01", "2014-12-31")
   @ano = {"trimetre1" => @t1, "trimestre2" =>@t2, "trimestre3" => @t3, "trimestre4" => @t4}
   @datos= { :size => '700x400',
            :theme => :thirty7signals, 
            :title => "enfermedad por trimestre", 
            :bg => 'EFF5FF', 
            :line_colors => 'B22222,0077CC, FFA500',
            :legend => @ano.keys,
            :data => @ano.values,
            :axis_range => [nil, [0,10,20,30,40,50,60,70,80,90,100]],
            :axis_with_labels => 'x,y',
            :labels => @ano.values }
 end

 
  

  def index 
    @enfermedads = Enfermedad.search(params[:search], params[:page]).order('fecha ASC') 
  end 
 
  def show 
  end 
 
  def new 
    @enfermedad = Enfermedad.new 
  end 
 
  def edit 
  end 
 
  def create 
   @enfermedad = Enfermedad.new(enfermedad_params) 
   render action: :new unless @enfermedad.save 
  end 
 
  def update 
    render action: :edit unless @enfermedad.update_attributes(enfermedad_params) 
  end 
 
  def destroy 
   @enfermedad.destroy 
  end 
 
  private 
  # Use callbacks to share common setup or constraints between actions. 
  def set_enfermedad
    @enfermedad = Enfermedad.find(params[:id]) 
  end 
 
  # Never trust parameters from the scary internet, only allow the white list through. 
  def enfermedad_params         
    params.require(:enfermedad).permit(:funcionario_id, :tipoenfermedad_id, :descripcion, :fecha, :codigodediagnostico) 
  end 

 
end 

app/helpers/enfermedads_helper.rb
module EnfermedadsHelper
        
        def showGrafica(tipoG,datosG)
        case(tipoG)
                when "pie_3d"
                         image_tag ( Gchart.pie_3d(datosG) )    
                when "line" 
                         image_tag ( Gchart.line(datosG) )              
                when "bar"
                         image_tag ( Gchart.bar(datosG) )                       
        end
        end     
end

app/views/enfermedads/_enfermedad.html.erb
<tr id=<%= "enfermedad_#{enfermedad.id}" %>> 
   
	<td><%= enfermedad.funcionario.nombres rescue nil %></td>
	<td><%= enfermedad.tipoenfermedad.nombre rescue nil %></td>
	<td><%= enfermedad.descripcion %></td>
	<td><%= enfermedad.fecha %></td>
	<td><%= enfermedad.codigodediagnostico %></td>
   
   <% if can? :read, enfermedad%>
    <td><%= link_to 'Ver', enfermedad, remote: true, class: "btn btn-success btn-xs" %></td>
    <%end%>
    <% if can? :update, enfermedad%>
    <td><%= link_to 'Editar', edit_enfermedad_path(enfermedad), remote: true, class: "btn btn-warning btn-xs" %></td>
    <%end%>
     <% if can? :destroy, enfermedad%>
    <td><%= link_to 'Eliminar', enfermedad, method: :delete, data: { confirm: 'Esta Seguro?' }, class: "btn btn-danger btn-xs", remote: true %></td>
    <%end%>
</tr>

app/views/enfermedads/_estadistica.html.erb
<%= showGrafica(@tipo,@datos) %>

<%= link_to 'Atras', static_pages_estadistica_path,:class=>'btn btn-info btn-xs'  %>

app/views/enfermedads/_form.html.erb
<%=simple_form_for(@enfermedad, :html => {:class => 'form­-horizontal', remote: true } ) do  |f| %>

  <% if @enfermedad.errors.any? %> 
      <div id="error_explanation"> 
       <h2><%= pluralize(@enfermedad.errors.count, "error")   %> prohibited this enfermedad from  
      being saved:</h2> 
       
  <ul> 
  <% @enfermedad.errors.full_messages.each do |message| %> 
  <li><%= message %></li> 
  <% end %> 
  </ul> 
  </div> 
<% end %> 

<div class="field">
    funcionarios <br>
    <%= f.collection_select :funcionario_id, Funcionario.all, :id, :nombres, class: "form-control", prompt:
    "Seleccione Funcionario" %>
  </div>
 

   <div class="form­-group"> 
    <label for="name" class="col-­sm-­3 control­-label">Descripción</label>  
    <div class="col­-md-­4"> 
       <%= f.input :descripcion, class: 'form­-control', :label => false %> 
    </div> 
   </div>


   <div class="form­-group"> 
    <label for="name" class="col-­sm-­3 control­-label">Fecha</label>  
    <div class="col­-md-­4"> 
       <%= f.text_field :fecha, class: 'datepicker' %>
        <script type="text/javascript">
         $('.datepicker').datepicker({
          language: "es",
          format: "yyyy/mm/dd",
          keyboardNavigation:false,
          forceParse:false,
          autoclose:true,
          todayHighlight:true,

        });
    </script>
    </div> 
   </div>

   <div class="form­-group"> 
    <label for="name" class="col-­sm-­3 control­-label">Codigo_de_diagnostico</label>  
    <div class="col­-md-­4"> 
       <%= f.input :codigodediagnostico, class: 'form­-control', :label => false %> 
    </div> 
   </div>

 <div class="field">
    <b>Tipo enfermedad<b> <br>
    <%= f.collection_select :tipoenfermedad_id, Tipoenfermedad.all, :id, :nombre, class: "form-control", prompt:
    "Seleccione Tipo enfermedad" %>
  </div>

<div class="form­-group"> 
   <div class="col­-sm­-offset­-2 col-­sm­-10"> 
   <%= f.submit "Guardar", class: "btn btn-info btn-xs" %> 
   <%= link_to 'Atras', enfermedads_path, class: "btn btn-default btn-xs" %>
   </div> 
</div> 
 
<% end %> 

app/views/enfermedads/_show.html.erb
<div class='enfermedad'> 

<p id="notice"><%= notice %></p>

<p>
  <strong>Funcionario:</strong>
  <%= @enfermedad.funcionario.nombres rescue nil %>
</p>

<p>
  <strong>Tipo de enfermedad:</strong>
  <%= @enfermedad.tipoenfermedad.nombre rescue nil %>
</p>


<p>
  <strong>Descripcion:</strong>
  <%= @enfermedad.descripcion %>
</p>

<p>
  <strong>fecha:</strong>
  <%= @enfermedad.fecha %>
</p>

<p>
  <strong>Codigo de diagnostico:</strong>
  <%= @enfermedad.codigodediagnostico %>
</p>



</div>

app/views/enfermedads/create.js.erb
$('table tbody').append("<%= escape_javascript(render @enfermedad) %>")
$.lazybox.close()

app/views/enfermedads/destroy.js.erb
$.lazybox.close()
$("table tr#enfermedad_<%= @enfermedad.id %>").remove();

app/views/enfermedads/edit.js.erb
$.lazybox("<%= j(render 'form') %>", {klass: 'custom'});

app/views/enfermedads/estadistica.js.erb
$.lazybox("<%=j(render 'estadistica')%>");

app/views/enfermedads/index.html.erb
<div class="index">
<center class="fadeIn"><h1><b>ENFERMEDADES</b></h1></center><br><br>

<div class="buscador">
	<%= form_tag enfermedads_path, :method => 'get' do %>
	<% content_tag :label do %>
	Fecha:
	<%= text_field_tag :search, params[:search] %>
	<%= submit_tag "Buscar", :name => nil %>
	<% end %>
	<% end %>
</div>

<div class="ctable">
<table class="table table-striped">
  <thead>
    <tr>
      <th>Funcionario</th>
      <th>Tipo de enfermedad</th>
       <th>Descripcion</th>
       <th>Fecha</th>
      <th>Codigo de diagnostico</th>
      
      <th colspan="3">Acciones</th>
    </tr>
  </thead>

  <tbody>
     <%= render @enfermedads %>
  </tbody>
</table>
</div>
<br>

 
 <% if can? :create, @enfermedad%>
<%= button_to 'Nueva Enfermedad', new_enfermedad_path, remote: true, :method=>"get", class: "btn btn-primary btn-xs" %> 
<%end%><br>

<div class="descarga">
<p>
  Descarga:
  <%= link_to "CSV", enfermedads_path(format: "csv") %> |
  <%= link_to "Excel", enfermedads_path(format: "xls") %>
</p>
</div>


<%= will_paginate @enfermedads, :previous_label => '&laquo; Anterior', :next_label => 'Siguiente &raquo;' %>
Enfermedads: <%= @enfermedads.count %>
 

</div>

app/views/enfermedads/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
      <Cell><Data ss:Type="INTEGER">id</Data></Cell> 
      <Cell><Data ss:Type="INTEGER">funcionario_id</Data></Cell> 
      <Cell><Data ss:Type="INTEGER">tipoenfermedad_id</Data></Cell> 
      <Cell><Data ss:Type="String">descripcion</Data></Cell> 
      <Cell><Data ss:Type="Date">fecha</Data></Cell> 
      <Cell><Data ss:Type="String">codigodediagnostico</Data></Cell> 
      <Cell><Data ss:Type="INTEGER">tipoenfermedad_id</Data></Cell> 
      </Row>
    <% @enfermedads.each do |enfermedads| %>
      <Row>
      <Cell><Data ss:Type="INTEGER"><%= enfermedad.id %></Data></Cell> 
      <Cell><Data ss:Type="INTEGER"><%= enfermedad .funcionario_id %></Data></Cell> 
      <Cell><Data ss:Type="INTEGER">tipoenfermedad_id</Data></Cell> 
      <Cell><Data ss:Type="String"><%= enfermedad .descripcion %></Data></Cell> 
      <Cell><Data ss:Type="Date"><%= enfermedad .fecha %></Data></Cell> 
      <Cell><Data ss:Type="String"><%= enfermedad .codigodediagnostico %></Data></Cell> 
      <Cell><Data ss:Type="INTEGER"><%= enfermedad.tipoenfermedad_id %></Data></Cell> 

       </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/enfermedads/new.js.erb
$.lazybox("<%= j(render partial: 'form') %>", { onTop: false });

app/views/enfermedads/show.js.erb
$.lazybox("<%= j(render 'show') %>", { closeImg: false, klass: 'sticker' })

app/views/enfermedads/update.js.erb
$('tr#enfermedad_<%= @enfermedad.id %>').replaceWith("<%= escape_javascript(render @enfermedad) %>")
$.lazybox.close()