config/routes.rb
Rails.application.routes.draw do

  resources :events
  resources :tipoincapacidads
  resources :tipoenfermedads
  resources :tiporiesgos
  resources :tipoincidentes
  resources :tipoaccidentes
  resources :albums
  resources :accidentes
  resources :municipios
  resources :departamentos
  

  get 'user_sessions/new'
  get 'user_sessions/create'
  get 'user_sessions/destroy'
  get 'email/send' => 'accidentes#enviar'
  
  resources :users

  match '/home', to: 'static_pages#home',  via: 'get' 
  match '/help',to: 'static_pages#help',  via: 'get' 
  match '/about',   to: 'static_pages#about',  via: 'get' 
  match '/contact', to: 'static_pages#contact',  via: 'get'
  match '/estadistica', to: 'static_pages#estadistica',  via: 'get' 
 
  root :to => 'user_sessions#index' 

  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/contact'
  get 'static_pages/about'
  get 'login' => 'user_sessions#new', :as => :login 
  get 'logout' => 'user_sessions#destroy', :as => :logout 
  get 'static_pages/estadistica'

  resources :incidentes
  resources :funcionarios

  resources :riesgos do 
    resources :tiporiesgos
  end

  resources :incapacidads do
    resources :tipoincapacidads
  end

  resources :accidentes do
    resources :tipoaccidentes
  end

  resources :enfermedads
  resources :personalinvolucrados
  resources :tipodocs
  resources :centros
  resources :user_sessions
  resources :users
  resources :cronogramas
  resources :tipo_salidas

  get 'incidentes_estadistica',to: 'incidentes#estadistica', :as => 'incidentes_estadistica'
  get 'riesgos_estadistica',to: 'riesgos#estadistica', :as => 'riesgos_estadistica'
  get 'enfermedads_estadistica',to: 'enfermedads#estadistica', :as => 'enfermedads_estadistica'
  get 'incapacidads_estadistica',to: 'incapacidads#estadistica', :as => 'incapacidads_estadistica'
  get 'accidentes_estadistica',to: 'accidentes#estadistica', :as => 'accidentes_estadistica'

  

   

end

app/models/incapacidad.rb
class Incapacidad < ActiveRecord::Base

	def self.search(search, page)
		where(['upper(fechainicio) like ?',
		"%#{search}%".upcase]).paginate(page: page, per_page: 5).order("fechainicio")
    end


  belongs_to :funcionario
  has_many :tipoincapacidad

   validates :funcionario_id, :presence => true 
   validates :fechainicio, :presence => true 
   validates :fechaterminacion, :presence => true 
   validates :totaldias, :presence => true 
   validates :diasacobrar, :presence => true 
   validates :prorroga, :presence => true 
   validates :numeroinpacacidad, :presence => true 
   validates :origendelaincapacidad, :presence => true 

   def self.estadistica_x_trimestre(fechIni, fechFin)
      @t1 = Incapacidad.select('count(*) as numero_incapacidads').where('fechainicio between  ? and  ?',fechIni,fechFin)
      @t1.pluck('count(*)').first
  end




def self.to_csv(options = {})
  CSV.generate(options) do |csv|
    csv << column_names
    all.each do |incapacidad|
      csv << incapacidad.attributes.values_at(*column_names)
    end
  end
end


   
end

app/controllers/incapacidads_controller.rb
class IncapacidadsController < ApplicationController
  
  before_action :set_incapacidad, only: [:show, :edit, :update, :destroy]


 def estadistica
   @tipo = params[:grafica] 
   @ano = Hash.new
   @t1 = Incapacidad.estadistica_x_trimestre("2014-01-01", "2014-03-30")
   @t2 = Incapacidad.estadistica_x_trimestre("2014-04-01", "2014-06-30")
   @t3 = Incapacidad.estadistica_x_trimestre("2014-07-01", "2014-09-30")
   @t4 = Incapacidad.estadistica_x_trimestre("2014-10-01", "2014-12-31")
   @ano = {"trimetre1" => @t1, "trimestre2" =>@t2, "trimestre3" => @t3, "trimestre4" => @t4}
   @datos= { :size => '700x400',
            :theme => :thirty7signals, 
            :title => "Incapacidad por trimestre", 
            :bg => 'EFF5FF', 
            :line_colors => 'B22222,0077CC, FFA500',
            :legend => @ano.keys,
            :data => @ano.values,
            :axis_range => [nil, [0,10,20,30,40,50,60,70,80,90,100]],
            :axis_with_labels => 'x,y',
            :labels => @ano.values }
 end


  def index
        @incapacidads = Incapacidad.search(params[:search], params[:page]).order('fechainicio ASC')
  end 
 
  def show 
  end 
 
  def new 
        @incapacidad = Incapacidad.new 
  end 
 
  def edit 
  end 
 
  def create 
       @incapacidad = Incapacidad.new(incapacidad_params) 
       render action: :new unless @incapacidad.save 
  end 
 
  def update 
        render action: :edit unless @incapacidad.update_attributes(incapacidad_params) 
  end 
 
  def destroy 
       @incapacidad.destroy 
  end 
 
  private 
  # Use callbacks to share common setup or constraints between actions. 
  def set_incapacidad
       @incapacidad = Incapacidad.find(params[:id]) 
  end 
 
  # Never trust parameters from the scary internet, only allow the white list through. 
  def incapacidad_params         

    params.require(:incapacidad).permit(:funcionario_id, :tipoincapacidad_id, :fechainicio, :fechaterminacion, :totaldias, :diasacobrar, :prorroga, :numeroinpacacidad, :esp, :origendelaincapacidad) 
    
  end 

 
end 




  

app/helpers/incapacidads_helper.rb
module IncapacidadsHelper

    def mostrartipoincapacidad(id)
        Tipoincapacidad.where(:id => id).pluck(:nombre).first
      end  
	
	def showGrafica(tipoG,datosG)
        case(tipoG)
        	when "pie_3d"
        		 image_tag ( Gchart.pie_3d(datosG) )	
        	when "line" 
        		 image_tag ( Gchart.line(datosG) )		
        	when "bar"
        		 image_tag ( Gchart.bar(datosG) )			
        end
	end	
end

app/views/incapacidads/_estadistica.html.erb
<%= showGrafica(@tipo,@datos) %>

<%= link_to 'Atras', static_pages_estadistica_path,:class=>'btn btn-info btn-xs' %>

app/views/incapacidads/_form.html.erb
<br><br><br>
<%=simple_form_for(@incapacidad, :html => {:class => 'form­horizontal', remote: true } ) do  |f| %>

  <% if @incapacidad.errors.any? %> 
  <div id="error_explanation"> 
    <h2><%= pluralize(@incapacidad.errors.count, "error") %> prohibited this incapacidad from  
      being saved:</h2>   
    <ul> 
      <% @incapacidad.errors.full_messages.each do |message| %> 
      <li><%= message %></li> 
      <% end %> 
    </ul> 
  </div> 

<% end %> 

<div class="field">
    funcionarios <br>
    <%= f.collection_select :funcionario_id, Funcionario.all, :id, :nombres, class: "form-control", prompt:
    "Seleccione Funcionario" %>
  </div>

   <div class="field">
    <b>Tipo de incapacidad</b><br>
    <%= f.collection_select :tipoincapacidad_id, Tipoincapacidad.all, :id, :nombre, class: "form-control", prompt:
    "Seleccione tipo de incapacidad" %>
  </div>
 

   <div class="form­-group"> 
    <label for="name" class="col-­sm-­3 control­-label">Fecha inicio</label>  
    <div class="col­-md-­4"> 
       <%= f.text_field :fechainicio, class: 'datepicker' %>
        <script type="text/javascript">
         $('.datepicker').datepicker({
          language: "es",
          format: "yyyy/mm/dd",
          keyboardNavigation:false,
          forceParse:false,
          autoclose:true,
          todayHighlight:true,

        });
    </script>
    </div> 
   </div>


   <div class="form­-group"> 
    <label for="name" class="col-­sm-­3 control­-label">Fecha terminacion</label>  
    <div class="col­-md-­4"> 
        <%= f.text_field :fechaterminacion, class: 'datepicker' %>
        <script type="text/javascript">
         $('.datepicker').datepicker({
          language: "es",
          format: "yyyy/mm/dd",
          keyboardNavigation:false,
          forceParse:false,
          autoclose:true,
          todayHighlight:true,

        });
    </script>
    </div> 
   </div>

  
 

   <div class="form­-group"> 
    <label for="name" class="col-­sm-­3 control­-label">Total dias</label>  
    <div class="col­-md-­4"> 
       <%= f.input :totaldias, class: 'form­-control', :label => false %> 
    </div> 
   </div>

   <div class="form­-group"> 
    <label for="name" class="col-­sm-­3 control­-label">Dias a cobrar</label>  
    <div class="col­-md-­4"> 
       <%= f.input :diasacobrar, class: 'form­-control', :label => false %> 
    </div> 
   </div>

   <div class="form­-group"> 
    <label for="name" class="col-­sm-­3 control­-label">Prorroga</label>  
    <div class="col­-md-­4"> 
       <%= f.input :prorroga, class: 'form­-control', :label => false %> 
    </div> 
   </div>

   <div class="form­-group"> 
    <label for="name" class="col-­sm-­3 control­-label">Numero inpacacidad</label>  
    <div class="col­-md-­4"> 
       <%= f.input :numeroinpacacidad, class: 'form­-control', :label => false %> 
    </div> 
   </div>

   <div class="form­-group"> 
    <label for="name" class="col-­sm-­3 control­-label">Origen de la incapacidad</label>  
    <div class="col­-md-­4"> 
       <%= f.input :origendelaincapacidad, class: 'form­-control', :label => false %> 
    </div> 
   </div>

 
<div class="form­-group"> 
   <div class="col­-sm­-offset­-2 col-­sm­-10"> 
   <%= f.submit "Guardar", class: "btn btn-info btn-xs" %> 
   <%= link_to 'Atras', incapacidads_path, class: "btn btn-default btn-xs" %>
   </div> 
</div> 
 

<% end %> 

app/views/incapacidads/_incapacidad.html.erb
<tr id=<%= "incapacidad_#{incapacidad.id}" %>> 
  
      <td><%= incapacidad.funcionario.nombres rescue nil %></td>
      <td><%= mostrartipoincapacidad(incapacidad.tipoincapacidad_id) %></td>
      <td><%= incapacidad.fechainicio %></td>
      <td><%= incapacidad.fechaterminacion %></td>
      <td><%= incapacidad.totaldias %></td>
      <td><%= incapacidad.diasacobrar %></td>
      <td><%= incapacidad.prorroga %></td>
      <td><%= incapacidad.numeroinpacacidad %></td>
      <td><%= incapacidad.origendelaincapacidad %></td>

      <% if can? :read, incapacidad%>
      <td><%= link_to 'Ver', incapacidad, remote: true,  class: "btn btn-success btn-xs" %></td>
      <%end%>
      <% if can? :update, incapacidad%>
      <td><%= link_to 'Editar', edit_incapacidad_path(incapacidad), remote: true, class: "btn btn-warning btn-xs" %></td>
      <%end%>
      <% if can? :destroy, incapacidad%>
      <td><%= link_to 'Eliminar', incapacidad, method: :delete, data: { confirm: 'Esta Seguro?' }, class: "btn btn-danger btn-xs", remote: true %></td>
      <%end%>
</tr>

app/views/incapacidads/_show.html.erb
<p>
  <strong>Funcionario:</strong>
  <%= @incapacidad.funcionario.nombres rescue nil%>
</p>

<p>
  <strong>Tipo de incapacidad:</strong>
  <%= mostrartipoincapacidad(@incapacidad.tipoincapacidad_id) %>

</p>

<p>
  <strong>Fecha inicio:</strong>
  <%= @incapacidad.fechainicio %>
</p>

<p>
  <strong>Fecha terminacion:</strong>
  <%= @incapacidad.fechaterminacion %>
</p>

<p>
  <strong>Total dias:</strong>
  <%= @incapacidad.totaldias %>
</p>

<p>
  <strong>Dias acobrar:</strong>
  <%= @incapacidad.diasacobrar %>
</p>

<p>
  <strong>Prorroga:</strong>
  <%= @incapacidad.prorroga %>
</p>

<p>
  <strong>Numero inpacacidad:</strong>
  <%= @incapacidad.numeroinpacacidad %>
</p>

<p>
  <strong>Origen de la incapacidad:</strong>
  <%= @incapacidad.origendelaincapacidad %>
</p>

app/views/incapacidads/create.js.erb
$('table tbody').append("<%= escape_javascript(render @incapacidad) %>")
$.lazybox.close()

app/views/incapacidads/destroy.js.erb
$.lazybox.close()
$("table tr#incapacidad_<%= @incapacidad.id %>").remove();

app/views/incapacidads/edit.js.erb
$.lazybox("<%= j(render :partial => 'form') %>", {klass: 'custom'});

app/views/incapacidads/estadistica.js.erb
$.lazybox("<%=j(render 'estadistica')%>");

app/views/incapacidads/index.html.erb
<div class="index">

<center class="fadeIn"><h1><b>INCAPACIDADES</b></h1></center><br><br>

<div class="buscador">
	<%= form_tag incapacidads_path, :method => 'get' do %>
	<% content_tag :label do %>
	Fecha inicio:
	<%= text_field_tag :search, params[:search] %>
	<%= submit_tag "Buscar", :name => nil %>
	<% end %>
	<% end %>
</div>

<div class="ctable">
<table class="table table-striped">
  <thead>
    <tr>
      <th>Funcionario</th>
       <th>Tipo de incapacidad</th>
      <th>Fecha inicio</th>
      <th>Fecha terminación</th>
      <th>Total dias</th>
      <th>Dias acobrar</th>
      <th>Prorroga</th>
      
      <th colspan="3">Acciones</th>
    </tr>
  </thead>

  <tbody>
     <%= render @incapacidads %>
  </tbody>
</table>
</div>
<br>

  <% if can? :create, @incapacidad%>
  <%= button_to 'Nueva Incapacidad', new_incapacidad_path, remote: true, :method=>"get", class: "btn btn-primary btn-xs" %> 
  <%end%><br>

<div class="descarga"><p>
  <p>
    Descarga:
    <%= link_to "CSV", incapacidads_path(format: "csv") %> |
    <%= link_to "Excel", incapacidads_path(format: "xls") %>
  </p>
</div>

  <%= will_paginate @incapacidads, :previous_label => '&laquo; Anterior', :next_label => 'Siguiente &raquo;' %>
  Incapacidads: <%= @incapacidads.count %>


</div>



 

app/views/incapacidads/new.js.erb
$.lazybox("<%= j(render partial: 'form') %>", { onTop: false });

app/views/incapacidads/show.js.erb
$.lazybox("<%= j(render 'show') %>", { closeImg: false, klass: 'sticker' })

app/views/incapacidads/update.js.erb
$('tr#incapacidad_<%= @incapacidad.id %>').replaceWith("<%= escape_javascript(render @incapacidad) %>")
$.lazybox.close()