config/routes.rb
Rails.application.routes.draw do

  resources :events
  resources :tipoincapacidads
  resources :tipoenfermedads
  resources :tiporiesgos
  resources :tipoincidentes
  resources :tipoaccidentes
  resources :albums
  resources :accidentes
  resources :municipios
  resources :departamentos
  

  get 'user_sessions/new'
  get 'user_sessions/create'
  get 'user_sessions/destroy'
  get 'email/send' => 'accidentes#enviar'
  
  resources :users

  match '/home', to: 'static_pages#home',  via: 'get' 
  match '/help',to: 'static_pages#help',  via: 'get' 
  match '/about',   to: 'static_pages#about',  via: 'get' 
  match '/contact', to: 'static_pages#contact',  via: 'get'
  match '/estadistica', to: 'static_pages#estadistica',  via: 'get' 
 
  root :to => 'user_sessions#index' 

  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/contact'
  get 'static_pages/about'
  get 'login' => 'user_sessions#new', :as => :login 
  get 'logout' => 'user_sessions#destroy', :as => :logout 
  get 'static_pages/estadistica'

  resources :incidentes
  resources :funcionarios

  resources :riesgos do 
    resources :tiporiesgos
  end

  resources :incapacidads do
    resources :tipoincapacidads
  end

  resources :accidentes do
    resources :tipoaccidentes
  end

  resources :enfermedads
  resources :personalinvolucrados
  resources :tipodocs
  resources :centros
  resources :user_sessions
  resources :users
  resources :cronogramas
  resources :tipo_salidas

  get 'incidentes_estadistica',to: 'incidentes#estadistica', :as => 'incidentes_estadistica'
  get 'riesgos_estadistica',to: 'riesgos#estadistica', :as => 'riesgos_estadistica'
  get 'enfermedads_estadistica',to: 'enfermedads#estadistica', :as => 'enfermedads_estadistica'
  get 'incapacidads_estadistica',to: 'incapacidads#estadistica', :as => 'incapacidads_estadistica'
  get 'accidentes_estadistica',to: 'accidentes#estadistica', :as => 'accidentes_estadistica'

  

   

end

app/models/accidente.rb
class Accidente < ActiveRecord::Base
	def self.search(search, page)
		where(['upper(fchAc) like ?',
		"%#{search}%".upcase]).paginate(page: page, per_page: 5).order("fchAc")
	end
  belongs_to :tipodoc
  belongs_to :departamento
  belongs_to :municipio
  belongs_to :funcionario

  # Validar que los atributos sean obligatorios
validates :diligenciador, :presence => true
validates :eps, :presence => true
validates :afp, :presence => true
validates :arl, :presence => true
validates :documento, :presence => true
validates :tipodoc_id, :presence => true
validates :tipo_de_vinculacion, :presence => true
validates :razon_social, :presence => true
validates :direccion_sede_principal, :presence => true
validates :direccion_reportada, :presence => true
validates :telefono_reportado, :presence => true
validates :actividad_economica_sede_principal, :presence => true
validates :codigo, :presence => true
validates :telefono_sede_principal, :presence => true
validates :fax_sede_principal, :presence => true
validates :email_sede_principal, :presence => true
validates :departamento_id, :presence => true
validates :municipio_id, :presence => true
validates :zona, :presence => true
validates :actividad_economica_centro_trabajo, :presence => true
validates :direccion_centro_trabajo, :presence => true
validates :telefono_ct, :presence => true
validates :fax_ct, :presence => true
validates :email_ct, :presence => true
validates :departamento1, :presence => true
validates :municipio1, :presence => true
validates :zona1, :presence => true
#validates :funcionario_id, :presence => true
validates :fchAc, :presence => true
validates :hora_del_accidente, :presence => true
validates :dia_de_la_semana, :presence => true
validates :jornada_en_que_sucede, :presence => true
#validates :realiza_su_labor, :presence => true
validates :ocupacion_no_habitual, :presence => true
validates :tiempo_laborado, :presence => true
validates :lugar_donde_ocurrio_el_at, :presence => true
validates :mecanismo_o_formato_del_at, :presence => true
validates :tipo_de_lesion, :presence => true
validates :sitio, :presence => true
#validates :tipo_de_accidente, :presence => true
validates :parte_del_cuerpo_afectado, :presence => true
validates :agente_del_accidente, :presence => true
validates :departamento2, :presence => true
validates :municipio2, :presence => true
validates :zona2, :presence => true
#validates :mortal, :presence => true
validates :fecha_mortal, :presence => true
validates :descripcion_del_at, :presence => true
#validates :hubo_personas_que_presenciaron_el_accidente, :presence => true
#validates :testigo1, :presence => true
#validates :tipodoc1, :presence => true
#validates :documento1, :presence => true
#validates :testigo2, :presence => true
#validates :tipodoc2, :presence => true
#validates :documento2, :presence => true
validates :responsable_informe, :presence => true
validates :tipodoc3, :presence => true
validates :documento3, :presence => true

#validar un atributo booleano
#validates :genero, inclusion: [true, false]

# validar formato de un email
validates :email_sede_principal, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i,
message: 'Formato no valido' }

validates :email_ct, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i,
message: 'Formato no valido' }

   def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |accidente|
        csv << accidente.attributes.values_at(*column_names)
      end
    end
  end



   def self.estadistica_x_trimestre(fechIni, fechFin)
        @t1 = Accidente.select('count(*) as numero_accidentes').where('fchAc between  ? and  ?',fechIni,fechFin)
        @t1.pluck('count(*)').first
    end

end

app/controllers/accidentes_controller.rb
class AccidentesController < ApplicationController
  before_action :set_accidente, only: [:show, :edit, :update, :destroy, :enviar]

  # GET /accidentes
  # GET /accidentes.json
 
   def estadistica
   @tipo = params[:grafica] 
   @ano = Hash.new
   @t1 = Accidente.estadistica_x_trimestre("2014-01-01", "2014-03-30")
   @t2 = Accidente.estadistica_x_trimestre("2014-04-01", "2014-06-30")
   @t3 = Accidente.estadistica_x_trimestre("2014-07-01", "2014-09-30")
   @t4 = Accidente.estadistica_x_trimestre("2014-10-01", "2014-12-31")
   @ano = {"trimetre1" => @t1, "trimestre2" =>@t2, "trimestre3" => @t3, "trimestre4" => @t4}
   @datos= { :size => '700x400',
            :theme => :thirty7signals, 
            :title => "Accidente por trimestre", 
            :bg => 'EFF5FF', 
            :line_colors => 'B22222,0077CC, FFA500',
            :legend => @ano.keys,
            :data => @ano.values,
            :axis_range => [nil, [0,10,20,30,40,50,60,70,80,90,100]],
            :axis_with_labels => 'x,y',
            :labels => @ano.values }
 end


  def index
    @accidentes = Accidente.search(params[:search], params[:page]).order('fchAc ASC')
  end

  # GET /accidentes/1
  # GET /accidentes/1.json
  def show
  end

  # GET /accidentes/new
  def new
    @accidente = Accidente.new
  end

  # GET /accidentes/1/edit
  def edit
  end

  # POST /accidentes
  # POST /accidentes.json
  def create
    @accidente = Accidente.new(accidente_params)

    respond_to do |format|
      if @accidente.save
        format.html { redirect_to @accidente, notice: 'El registro fue creado exitosamente.' }
        format.json { render :show, status: :created, location: @accidente }
      else
        format.html { render :new }
        format.json { render json: @accidente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accidentes/1
  # PATCH/PUT /accidentes/1.json
  def update
    respond_to do |format|
      if @accidente.update(accidente_params)
        format.html { redirect_to @accidente, notice: 'El registro fue actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @accidente }
      else
        format.html { render :edit }
        format.json { render json: @accidente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accidentes/1
  # DELETE /accidentes/1.json
  def destroy
    @accidente.destroy
    respond_to do |format|
      format.html { redirect_to accidentes_url, notice: 'El registro fue eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  def enviar  
    @accidente = Accidente.find(params[:id])  
    ActionCorreo.bienvenido_email(@accidente).deliver
        #render :show 
    redirect_to @accidente, notice: "Correo enviado exitosamente" 

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_accidente
      @accidente = Accidente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def accidente_params
      params.require(:accidente).permit(:diligenciador, :eps, :afp, :arl, :documento, :tipodoc_id, :tipo_de_vinculacion, :razon_social, :direccion_sede_principal, :direccion_reportada, :telefono_reportado, :actividad_economica_sede_principal, :codigo, :telefono_sede_principal, :fax_sede_principal, :email_sede_principal, :departamento_id, :municipio_id, :zona, :actividad_economica_centro_trabajo, :direccion_centro_trabajo, :telefono_ct, :fax_ct, :email_ct, :departamento1, :municipio1, :zona1, :funcionario_id, :fchAc, :hora_del_accidente, :dia_de_la_semana, :jornada_en_que_sucede, :realiza_su_labor, :ocupacion_no_habitual, :tiempo_laborado, :lugar_donde_ocurrio_el_at, :mecanismo_o_formato_del_at, :tipo_de_lesion, :sitio, :tipo_de_accidente, :parte_del_cuerpo_afectado, :agente_del_accidente, :departamento2, :municipio2, :zona2, :mortal, :fecha_mortal, :descripcion_del_at, :hubo_personas_que_presenciaron_el_accidente, :testigo1, :tipodoc1, :documento1, :testigo2, :tipodoc2, :documento2, :responsable_informe, :tipodoc3, :documento3)
    end
end

app/helpers/accidentes_helper.rb
module AccidentesHelper
	def mostrardoc(id)
		Tipodoc.where(:id => id).pluck(:nombre).first
	end
	def mostrarmun(id)
		Municipio.where(:id => id).pluck(:nombre).first
	end	
	def mostrardep(id)
		Departamento.where(:id => id).pluck(:nombre).first
	end	
	def mostrarrealiza_su_labor(realiza_su_labor)
		if realiza_su_labor
			"si"
		  else
			"no"
		end
	end
	def mostrarmortal(mortal)
		if mortal
			"si"
		  else
			"no"
		end
	end
	def mostrarhubo_personas_que_presenciaron_el_accidente(hubo_personas_que_presenciaron_el_accidente)
		if hubo_personas_que_presenciaron_el_accidente
			"si"
		  else
			"no"
		end
	end

	def showGrafica(tipoG,datosG)
        case(tipoG)
        	when "pie_3d"
        		 image_tag ( Gchart.pie_3d(datosG) )	
        	when "line" 
        		 image_tag ( Gchart.line(datosG) )		
        	when "bar"
        		 image_tag ( Gchart.bar(datosG) )			
        end
	end

	def mostrartipoaccidente(id)
		Tipoaccidente.where(:id => id).pluck(:nombre).first
	end		
end

app/views/accidentes/_estadistica.html.erb
<%= showGrafica(@tipo,@datos) %>

<%= link_to 'Atras', static_pages_estadistica_path,:class=>'btn btn-info btn-xs' %>

app/views/accidentes/edit.html.erb
<h1>Editar accidente</h1>
<%= render 'form' %>

app/views/accidentes/estadistica.js.erb
$.lazybox("<%=j(render 'estadistica')%>");

app/views/accidentes/index.html.erb
<div class="index">

<center class="fadeIn"><h1><b>ACCIDENTES</b></h1></center><br><br>
<div class="buscador">
<%= form_tag accidentes_path, :method => 'get' do %>
      <% content_tag :label do %>
        Buscar por fecha de accidente:
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "Buscar", :fecha_del_accidente => nil %>
      <% end %>
    <% end %>
  </div>
<div class="ctable">
<table class="table table-striped">
  <thead>
    <tr>
      <th>Diligenciador</th>  
      <th>Funcionario</th>
      <th>Fecha del accidente</th>
      <th>Hora del accidente</th>
      <th>Dia de la semana</th>
      <th>Lugar donde ocurrio el at</th>
      <th>Tipo de lesion</th>
      <th>Sitio</th>
      <th>Tipo de accidente</th>
      <th>Parte del cuerpo afectado</th>
      <th>Agente del accidente</th>
      <th>Descripcion del at</th>
      <th>Responsable informe</th>
      <th colspan="3">Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @accidentes.each do |accidente| %>
      <tr>
        <td><%= accidente.diligenciador %></td>
        <td><%= accidente.funcionario.nombres rescue nil %></td>
        <td><%= accidente.fchAc %></td>
        <td><%= accidente.hora_del_accidente %></td>
        <td><%= accidente.dia_de_la_semana %></td>
        <td><%= accidente.lugar_donde_ocurrio_el_at %></td>
        <td><%= accidente.tipo_de_lesion %></td>
        <td><%= accidente.sitio %></td>
        <td><%= mostrartipoaccidente(accidente.tipo_de_accidente) %></td>
        <td><%= accidente.parte_del_cuerpo_afectado %></td>
        <td><%= accidente.agente_del_accidente %></td>
        <td><%= accidente.descripcion_del_at %></td>
        <td><%= accidente.responsable_informe %></td>
        
        <% if can? :read, accidente %>
        <td><%= link_to 'Ver', accidente, class: "btn btn-success btn-xs" %></td>
         <%end%>
        <% if can? :update, accidente %>
        <td><%= link_to 'Editar', edit_accidente_path(accidente), class: "btn btn-warning btn-xs" %></td>
         <%end%>
        <% if can? :destroy, accidente %>
        <td><%= link_to 'Eliminar', accidente, class: "btn btn-danger btn-xs", method: :delete, data: { confirm: 'Esta seguro?' } %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<% if can? :create, @accidente %>
<%= link_to 'Nuevo Accidente', new_accidente_path, class: "btn btn-primary btn-xs" %>
<%end%><br>

<div class="descarga"><p>
<p>
  Descarga:
  <%= link_to "CSV", accidentes_path(format: "csv") %> |
  <%= link_to "Excel", accidentes_path(format: "xls") %>
</p>
</div>

<%= will_paginate @accidentes, :previous_label => '&laquo; Anterior', :next_label => 'Siguiente
&raquo;' %>
Accidentes: <%= @accidentes.count %>

</div>

app/views/accidentes/new.html.erb
<%= render 'form' %>

app/views/accidentes/show.html.erb
<div class="formulario">

<p id="notice"><%= notice %></p>

<p>
  <strong>Diligenciador:</strong>
  <%= @accidente.diligenciador %>
</p>

<p>
  <strong>Eps:</strong>
  <%= @accidente.eps %>
</p>

<p>
  <strong>Afp:</strong>
  <%= @accidente.afp %>
</p>

<p>
  <strong>Arl:</strong>
  <%= @accidente.arl %>
</p>

<p>
  <strong>Documento:</strong>
  <%= @accidente.documento %>
</p>

<p>
  <strong>Tipodoc:</strong>
  <%= @accidente.tipodoc.nombre rescue nil %>
</p>

<p>
  <strong>Tipo de vinculacion:</strong>
  <%= @accidente.tipo_de_vinculacion %>
</p>

<p>
  <strong>Razon social:</strong>
  <%= @accidente.razon_social %>
</p>

<p>
  <strong>Direccion sede principal:</strong>
  <%= @accidente.direccion_sede_principal %>
</p>

<p>
  <strong>Direccion reportada:</strong>
  <%= @accidente.direccion_reportada %>
</p>

<p>
  <strong>Telefono reportado:</strong>
  <%= @accidente.telefono_reportado %>
</p>

<p>
  <strong>Actividad economica sede principal:</strong>
  <%= @accidente.actividad_economica_sede_principal %>
</p>

<p>
  <strong>Codigo:</strong>
  <%= @accidente.codigo %>
</p>

<p>
  <strong>Telefono sede principal:</strong>
  <%= @accidente.telefono_sede_principal %>
</p>

<p>
  <strong>Fax sede principal:</strong>
  <%= @accidente.fax_sede_principal %>
</p>

<p>
  <strong>Email sede principal:</strong>
  <%= @accidente.email_sede_principal %>
</p>

<p>
  <strong>Departamento:</strong>
  <%= @accidente.departamento.nombre rescue nil %>
</p>

<p>
  <strong>Municipio:</strong>
  <%= @accidente.municipio.nombre rescue nil %>
</p>

<p>
  <strong>Zona:</strong>
  <%= @accidente.zona %>
</p>

<p>
  <strong>Actividad economica centro trabajo:</strong>
  <%= @accidente.actividad_economica_centro_trabajo %>
</p>

<p>
  <strong>Direccion centro trabajo:</strong>
  <%= @accidente.direccion_centro_trabajo %>
</p>

<p>
  <strong>Telefono ct:</strong>
  <%= @accidente.telefono_ct %>
</p>

<p>
  <strong>Fax ct:</strong>
  <%= @accidente.fax_ct %>
</p>

<p>
  <strong>Email ct:</strong>
  <%= @accidente.email_ct %>
</p>

<p>
  <strong>Departamento:</strong>
  <%= mostrardep(@accidente.departamento1) %>
</p>

<p>
  <strong>Municipio:</strong>
  <%= mostrarmun(@accidente.municipio1) %>
</p>

<p>
  <strong>Zona:</strong>
  <%= @accidente.zona1 %>
</p>

<p>
  <strong>Funcionario:</strong>
  <%= @accidente.funcionario.nombres rescue nil %>
</p>

<p>
  <strong>Fecha del accidente:</strong>
  <%= @accidente.fchAc %>
</p>

<p>
  <strong>Hora del accidente:</strong>
  <%= @accidente.hora_del_accidente %>
</p>

<p>
  <strong>Dia de la semana:</strong>
  <%= @accidente.dia_de_la_semana %>
</p>

<p>
  <strong>Jornada en que sucede:</strong>
  <%= @accidente.jornada_en_que_sucede %>
</p>

<p>
  <strong>Realiza su labor:</strong>
  <%= mostrarrealiza_su_labor(@accidente.realiza_su_labor) %>
</p>

<p>
  <strong>Ocupacion no habitual:</strong>
  <%= @accidente.ocupacion_no_habitual %>
</p>

<p>
  <strong>Tiempo laborado:</strong>
  <%= @accidente.tiempo_laborado %>
</p>

<p>
  <strong>Lugar donde ocurrio el at:</strong>
  <%= @accidente.lugar_donde_ocurrio_el_at %>
</p>

<p>
  <strong>Mecanismo o formato del at:</strong>
  <%= @accidente.mecanismo_o_formato_del_at %>
</p>

<p>
  <strong>Tipo de lesion:</strong>
  <%= @accidente.tipo_de_lesion %>
</p>

<p>
  <strong>Sitio:</strong>
  <%= @accidente.sitio %>
</p>

<p>
  <strong>Tipo de accidente:</strong>
  <%= mostrartipoaccidente(@accidente.tipo_de_accidente) %>
</p>

<p>
  <strong>Parte del cuerpo afectado:</strong>
  <%= @accidente.parte_del_cuerpo_afectado %>
</p>

<p>
  <strong>Agente del accidente:</strong>
  <%= @accidente.agente_del_accidente %>
</p>

<p>
  <strong>Departamento:</strong>
  <%= mostrardep(@accidente.departamento2) %>
</p>

<p>
  <strong>Municipio:</strong>
  <%= mostrarmun(@accidente.municipio2) %>
</p>

<p>
  <strong>Zona:</strong>
  <%= @accidente.zona2 %>
</p>

<p>
  <strong>Mortal:</strong>
  <%= mostrarmortal(@accidente.mortal) %>
</p>

<p>
  <strong>Fecha mortal:</strong>
  <%= @accidente.fecha_mortal %>
</p>

<p>
  <strong>Descripcion del at:</strong>
  <%= @accidente.descripcion_del_at %>
</p>

<p>
  <strong>Hubo personas que presenciaron el accidente:</strong>
<%= mostrarhubo_personas_que_presenciaron_el_accidente(@accidente.hubo_personas_que_presenciaron_el_accidente) %>
</p>

<p>
  <strong>Testigo1:</strong>
  <%= @accidente.testigo1 %>
</p>

<p>
  <strong>Tipodoc:</strong>
  <%= mostrardoc(@accidente.tipodoc1) %>
</p>

<p>
  <strong>Documento:</strong>
  <%= @accidente.documento1 %>
</p>

<p>
  <strong>Testigo2:</strong>
  <%= @accidente.testigo2 %>
</p>

<p>
  <strong>Tipodoc:</strong>
  <%= mostrardoc(@accidente.tipodoc2) %>
</p>

<p>
  <strong>Documento:</strong>
  <%= @accidente.documento2 %>
</p>

<p>
  <strong>Responsable informe:</strong>
  <%= @accidente.responsable_informe %>
</p>

<p>
  <strong>Tipodoc:</strong>
  <%= mostrardoc(@accidente.tipodoc3) %>
</p>

<p>
  <strong>Documento:</strong>
  <%= @accidente.documento3 %>
</p>

<% if can? :update, @accidente %>
<p class="text-center"><%= link_to 'Editar', edit_accidente_path(@accidente), class: "btn btn-warning btn-xs"  %>
<%end%> |
  <%= link_to 'Atras', accidentes_path, class: "btn btn-default btn-xs" %>

</p>
  
    <%= link_to 'Enviar al correo', email_send_path(:id => @accidente.id), :class=>'btn btn-info btn-xs' %>

</div>